version: "3.8"

services:
    db:
        image: postgres:14
        volumes:
            - ./_db_data:/var/lib/postgresql/data
            - ./initdb/init.sql:/docker-entrypoint-initdb.d/init.sql
        env_file: .env
        ports:
            - 5432:5432
